[package]
name = "http-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = {workspace = true}
thiserror = {workspace = true}
http = {workspace = true}
log = {workspace = true}
async-trait = {workspace = true}
anyhow = {workspace = true}

